### ISSUE TITLE
JVM.dll not found.

### ISSUE THREAD

**Issue by goopy13** [rage/tmc-vscode#628]
**Describe the bug**
jvm.dll not found with AdoptOpenJDK installed.

**To Reproduce**
1. Download & install AdoptOpenJDK 11 HotSpot.
2. Open vscode and try to run the tests.
3. See error: 
```
Runtime Error
Failed to run tests for exercise at c:\Users\Jai\Desktop\mooc\mooc-java-programming-i\part04-Part04_16.PaymentCard
Details:
Caused by: Failed to run tests for exercise at c:\Users\Jai\Desktop\mooc\mooc-java-programming-i\part04-Part04_16.PaymentCard
Caused by: Error in plugin
Caused by: J4rs panicked: Could find the jvm dynamic library: JavaLocatorError { description: "Could not find the jvm.dll library in any subdirectory of C:\\Program Files\\AdoptOpenJDK\\jdk-11.0.11.9-hotspot\\bin\\java.exe\r\nC:\\Program Files (x86)\\Common Files\\Oracle\\Java" }
Error stack
Runtime Error: Failed to run tests for exercise at c:\Users\Jai\Desktop\mooc\mooc-java-programming-i\part04-Part04_16.PaymentCard
	at p._checkLangsResponse (c:\Users\Jai\.vscode\extensions\moocfi.test-my-code-2.1.0\dist\lib.js:2:587310)
	at c:\Users\Jai\.vscode\extensions\moocfi.test-my-code-2.1.0\dist\lib.js:2:410705
	at e.andThen (c:\Users\Jai\.vscode\extensions\moocfi.test-my-code-2.1.0\dist\lib.js:2:719047)
	at c:\Users\Jai\.vscode\extensions\moocfi.test-my-code-2.1.0\dist\lib.js:2:410688
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Expected behavior**
Test runs.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11 22000.100
 - VSCode Version 1.58.2
 - TMC Extension Version 2.1.0

**TMC Extension logs**
```
[2021-08-02 14:38:31:453] [INFO] Starting moocfi.test-my-code in "production" mode.
[2021-08-02 14:38:31:453] [INFO] Visual Studio Code version: 1.58.2
[2021-08-02 14:38:31:453] [INFO] moocfi.test-my-code version: 2.1.0
[2021-08-02 14:38:31:453] [INFO] Currently open workspace: mooc-java-programming-i (Workspace)
[2021-08-02 14:38:31:454] [INFO] Platform win32 Arch x64
[2021-08-02 14:38:31:454] [INFO] TMC-Langs version: tmc-langs-cli-x86_64-pc-windows-msvc-0.21.0-beta-4.exe
[2021-08-02 14:38:31:454] [INFO] Run: "c:\\Users\\Jai\\AppData\\Roaming\\Code\\User\\globalStorage\\moocfi.test-my-code\\cli\\tmc-langs-cli-x86_64-pc-windows-msvc-0.21.0-beta-4.exe" "--client-name" "vscode_plugin" "--client-version" "2.1.0" "core" "logged-in"
[2021-08-02 14:38:31:846] [INFO] Run: "c:\\Users\\Jai\\AppData\\Roaming\\Code\\User\\globalStorage\\moocfi.test-my-code\\cli\\tmc-langs-cli-x86_64-pc-windows-msvc-0.21.0-beta-4.exe" "--client-name" "vscode_plugin" "--client-version" "2.1.0" "settings" "get" "projects-dir"
[2021-08-02 14:38:32:095] [INFO] TMC Workspace open, verifying workspace settings integrity.
[2021-08-02 14:38:32:240] [INFO] Run: "c:\\Users\\Jai\\AppData\\Roaming\\Code\\User\\globalStorage\\moocfi.test-my-code\\cli\\tmc-langs-cli-x86_64-pc-windows-msvc-0.21.0-beta-4.exe" "--client-name" "vscode_plugin" "--client-version" "2.1.0" "list-local-course-exercises" "--course-slug" "mooc-java-programming-i"
[2021-08-02 14:38:32:487] [INFO] Run: "c:\\Users\\Jai\\AppData\\Roaming\\Code\\User\\globalStorage\\moocfi.test-my-code\\cli\\tmc-langs-cli-x86_64-pc-windows-msvc-0.21.0-beta-4.exe" "--client-name" "vscode_plugin" "--client-version" "2.1.0" "settings" "get" "closed-exercises-for:mooc-java-programming-i"
[2021-08-02 14:38:32:725] [INFO] Initializing UI Actions
[2021-08-02 14:38:32:725] [INFO] Registering TMC VSCode commands
[2021-08-02 14:38:32:726] [INFO] Checking for exercise updates
[2021-08-02 14:38:32:726] [INFO] Checking for exercise updates, forced update: false
[2021-08-02 14:38:32:726] [INFO] Run: "c:\\Users\\Jai\\AppData\\Roaming\\Code\\User\\globalStorage\\moocfi.test-my-code\\cli\\tmc-langs-cli-x86_64-pc-windows-msvc-0.21.0-beta-4.exe" "--client-name" "vscode_plugin" "--client-version" "2.1.0" "core" "check-exercise-updates"
[2021-08-02 14:38:32:730] [INFO] Checking for course updates for courses mooc-java-programming-i
[2021-08-02 14:38:32:730] [INFO] Run: "c:\\Users\\Jai\\AppData\\Roaming\\Code\\User\\globalStorage\\moocfi.test-my-code\\cli\\tmc-langs-cli-x86_64-pc-windows-msvc-0.21.0-beta-4.exe" "--client-name" "vscode_plugin" "--client-version" "2.1.0" "core" "get-course-data" "--course-id" "600"
[2021-08-02 14:38:33:791] [INFO] Update check found 0 outdated exercises
[2021-08-02 14:38:36:262] [INFO] Active text document language: java
[2021-08-02 14:38:36:262] [INFO] Run: "c:\\Users\\Jai\\AppData\\Roaming\\Code\\User\\globalStorage\\moocfi.test-my-code\\cli\\tmc-langs-cli-x86_64-pc-windows-msvc-0.21.0-beta-4.exe" "--client-name" "vscode_plugin" "--client-version" "2.1.0" "run-tests" "--exercise-path" "c:\\Users\\Jai\\Desktop\\mooc\\mooc-java-programming-i\\part04-Part04_16.PaymentCard"
[2021-08-02 14:38:36:274] [INFO] Running local tests for part04-Part04_16.PaymentCard
[2021-08-02 14:38:36:509] [INFO] Rust Langs
[2021-08-02T14:38:36Z DEBUG tmc_langs] running tests in c:\Users\Jai\Desktop\mooc\mooc-java-programming-i\part04-Part04_16.PaymentCard

[2021-08-02 14:38:36:509] [INFO] Rust Langs
[2021-08-02T14:38:36Z DEBUG tmc_langs_framework::tmc_project_yml] reading .tmcproject.yml from c:\Users\Jai\Desktop\mooc\mooc-java-programming-i\part04-Part04_16.PaymentCard\.tmcproject.yml

[2021-08-02 14:38:36:509] [INFO] Rust Langs
[2021-08-02T14:38:36Z INFO  tmc_langs_plugins] Detected project at c:\Users\Jai\Desktop\mooc\mooc-java-programming-i\part04-Part04_16.PaymentCard as apache-maven

[2021-08-02 14:38:36:513] [INFO] Rust Langs
[2021-08-02T14:38:36Z DEBUG tmc_langs_java] updating tmc junit runner jar

[2021-08-02 14:38:36:513] [INFO] Rust Langs
[2021-08-02T14:38:36Z DEBUG tmc_langs_java] junit runner at C:\Users\Jai\AppData\Local\tmc\tmc-junit-runner.jar

[2021-08-02 14:38:36:525] [INFO] Rust Langs
[2021-08-02T14:38:36Z DEBUG tmc_langs_java] checkstyle runner at C:\Users\Jai\AppData\Local\tmc\tmc-checkstyle-runner.jar

[2021-08-02 14:38:36:529] [INFO] Rust Langs
[2021-08-02T14:38:36Z DEBUG tmc_langs_java] initialized jassets at C:\Users\Jai\AppData\Local\tmc\jassets\j4rs.jar

[2021-08-02 14:38:36:529] [INFO] Rust Langs
[2021-08-02T14:38:36Z INFO  j4rs::logger] Setting classpath to -Djava.class.path=C:\Users\Jai\AppData\Local\tmc\jassets\j4rs.jar;C:\Users\Jai\AppData\Local\tmc\tmc-junit-runner.jar;C:\Users\Jai\AppData\Local\tmc\tmc-checkstyle-runner.jar
[2021-08-02T14:38:36Z INFO  j4rs::logger] Setting library path to -Djava.library.path=C:\Users\Jai\AppData\Local\tmc\deps

[2021-08-02 14:38:36:529] [INFO] Rust Langs
[2021-08-02T14:38:36Z DEBUG j4rs::logger] Creating a Jvm

[2021-08-02 14:38:36:589] [INFO] Rust Langs
thread 'main' panicked at 'Could find the jvm dynamic library: JavaLocatorError { description: "Could not find the jvm.dll library in any subdirectory of C:\\Program Files\\AdoptOpenJDK\\jdk-11.0.11.9-hotspot\\bin\\java.exe\r\nC:\\Program Files (x86)\\Common Files\\Oracle\\Java" }', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\j4rs-0.13.0\src\api_tweaks\generic.rs:41:38
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

[2021-08-02 14:38:36:598] [ERROR] Exercise test run failed.
Runtime Error — Failed to run tests for exercise at c:\Users\Jai\Desktop\mooc\mooc-java-programming-i\part04-Part04_16.PaymentCard — Runtime Error: Failed to run tests for exercise at c:\Users\Jai\Desktop\mooc\mooc-java-programming-i\part04-Part04_16.PaymentCard
	at p._checkLangsResponse (c:\Users\Jai\.vscode\extensions\moocfi.test-my-code-2.1.0\dist\lib.js:2:587310)
	at c:\Users\Jai\.vscode\extensions\moocfi.test-my-code-2.1.0\dist\lib.js:2:410705
	at e.andThen (c:\Users\Jai\.vscode\extensions\moocfi.test-my-code-2.1.0\dist\lib.js:2:719047)
	at c:\Users\Jai\.vscode\extensions\moocfi.test-my-code-2.1.0\dist\lib.js:2:410688
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Additional context**
Looks like TMC is looking for jvm.dll in `C:/Program\ Files/AdoptOpenJDK/jdk-11.0.11.9-hotspot/bin` instead of its actual location of the client and server folders inside of bin.

**Comment by goopy13** [comment]
Oops, I forgot to enable "Set JAVA_HOME variable" and "JavaSoft (Oracle) registry keys" during the installation.

**Comment by serpatsama** [comment]
I still have this issue

```
Details:
Caused by: Failed to run tests for exercise at c:\Users\DESKTOP\AppData\Roaming\Code\User\globalStorage\moocfi.test-my-code\workspaces\.tmc\tmcdata\mooc-java-programming-i\part01-Part01_05.Message
Caused by: Error in plugin
Caused by: J4rs panicked: Could find the jvm dynamic library: JavaLocatorError { description: "Could not find the jvm.dll library in any subdirectory of C:\\Program Files\\Common Files\\Oracle\\Java\\javapath\\java.exe\r\nC:\\Program Files (x86)\\Common Files\\Oracle\\Java" }
```

**Comment by serpatsama** [comment]
@goopy13 I see no such options in the installer.

However the java bin folder is in path.
