### ISSUE TITLE
Runtime Error Caused by: Error in plugin Caused by: J4rs panicked: Could not load the jvm dynamic library: DlOpen

### ISSUE THREAD

**Issue by rjhefley** [rage/tmc-vscode#677]
**Error Caused By Error in plugin caused by J4rs panicked: Could not load the jvm dynamic library**

The exercise runs fine when running via console. However, I cannot use the TMC Run Tests button due to error found below

I made sure that I had the correct ARM version of JDK

```
Runtime Error
Failed to run tests for exercise at /Users/ryan/Code/TMC/mooc-java-programming-i/part03-Part03_15.PrintInRange
Details:
Caused by: Failed to run tests for exercise at /Users/ryan/Code/TMC/mooc-java-programming-i/part03-Part03_15.PrintInRange
Caused by: Error in plugin
Caused by: J4rs panicked: Could not load the jvm dynamic library: DlOpen { desc: "dlopen(/Library/Java/JavaVirtualMachines/jdk-17.jdk/Contents/Home/lib/server/libjvm.dylib, 0x0002): tried: \'/Library/Java/JavaVirtualMachines/jdk-17.jdk/Contents/Home/lib/server/libjvm.dylib\' (mach-o file, but is an incompatible architecture (have \'arm64\', need \'x86_64\')), \'/System/Volumes/Preboot/Cryptexes/OS/Library/Java/JavaVirtualMachines/jdk-17.jdk/Contents/Home/lib/server/libjvm.dylib\' (no such file), \'/Library/Java/JavaVirtualMachines/jdk-17.jdk/Contents/Home/lib/server/libjvm.dylib\' (mach-o file, but is an incompatible architecture (have \'arm64\', need \'x86_64\'))" }
Error stack
Runtime Error: Failed to run tests for exercise at /Users/ryan/Code/TMC/mooc-java-programming-i/part03-Part03_15.PrintInRange
	at u._checkLangsResponse (/Users/ryan/.vscode/extensions/moocfi.test-my-code-2.1.5/dist/lib.js:2:436918)
	at /Users/ryan/.vscode/extensions/moocfi.test-my-code-2.1.5/dist/lib.js:2:381755
	at e.andThen (/Users/ryan/.vscode/extensions/moocfi.test-my-code-2.1.5/dist/lib.js:2:543900)
	at /Users/ryan/.vscode/extensions/moocfi.test-my-code-2.1.5/dist/lib.js:2:381738
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Desktop (please complete the following information):**
MAC OS 13.4
VS CODE: Version: 1.81.1 (Universal)
TMC VERSION 2.1.5

**TMC Extension logs**
[2023-08-17 17:48:35:808] [INFO] Active text document language: java
[2023-08-17 17:48:35:808] [INFO] Run: "/Users/ryan/Library/Application Support/Code/User/globalStorage/moocfi.test-my-code/cli/tmc-langs-cli-aarch64-apple-darwin-0.25.2" "--client-name" "vscode_plugin" "--client-version" "2.1.5" "run-tests" "--exercise-path" "/Users/ryan/Code/TMC/mooc-java-programming-i/part03-Part03_15.PrintInRange"
[2023-08-17 17:48:35:813] [INFO] Running local tests for part03-Part03_15.PrintInRange
[2023-08-17 17:48:35:847] [INFO] Rust Langs
[2023-08-17T17:48:35Z DEBUG tmc_langs] running tests in /Users/ryan/Code/TMC/mooc-java-programming-i/part03-Part03_15.PrintInRange
[2023-08-17T17:48:35Z DEBUG tmc_langs_framework::tmc_project_yml] reading .tmcproject.yml from /Users/ryan/Code/TMC/mooc-java-programming-i/part03-Part03_15.PrintInRange/.tmcproject.yml

[2023-08-17 17:48:35:848] [INFO] Rust Langs
[2023-08-17T17:48:35Z INFO  tmc_langs_plugins] Detected project at /Users/ryan/Code/TMC/mooc-java-programming-i/part03-Part03_15.PrintInRange as apache-maven

[2023-08-17 17:48:35:848] [INFO] Rust Langs
[2023-08-17T17:48:35Z DEBUG tmc_langs_java] updating tmc junit runner jar

[2023-08-17 17:48:35:848] [INFO] Rust Langs
[2023-08-17T17:48:35Z DEBUG tmc_langs_java] junit runner at /Users/ryan/Library/Caches/tmc/tmc-junit-runner.jar

[2023-08-17 17:48:35:853] [INFO] Rust Langs
[2023-08-17T17:48:35Z DEBUG tmc_langs_java] checkstyle runner at /Users/ryan/Library/Caches/tmc/tmc-checkstyle-runner.jar

[2023-08-17 17:48:35:854] [INFO] Rust Langs
[2023-08-17T17:48:35Z DEBUG tmc_langs_java] initialized jassets at /Users/ryan/Library/Caches/tmc/jassets/j4rs.jar

[2023-08-17 17:48:35:854] [INFO] Rust Langs
[2023-08-17T17:48:35Z INFO  j4rs::logger] Setting classpath to -Djava.class.path=/Users/ryan/Library/Caches/tmc/jassets/j4rs.jar:/Users/ryan/Library/Caches/tmc/tmc-junit-runner.jar:/Users/ryan/Library/Caches/tmc/tmc-checkstyle-runner.jar
[2023-08-17T17:48:35Z INFO  j4rs::logger] Setting library path to -Djava.library.path=/Users/ryan/Library/Caches/tmc/deps:/usr/lib:/lib
[2023-08-17T17:48:35Z DEBUG j4rs::logger] Creating a Jvm

[2023-08-17 17:48:35:872] [INFO] Rust Langs
thread 'main' panicked at 'Could not load the jvm dynamic library: DlOpen { desc: "dlopen(/Library/Java/JavaVirtualMachines/jdk-17.jdk/Contents/Home/lib/server/libjvm.dylib, 0x0002): tried: \'/Library/Java/JavaVirtualMachines/jdk-17.jdk/Contents/Home/lib/server/libjvm.dylib\' (mach-o file, but is an incompatible architecture (have \'arm64\', need \'x86_64\')), \'/System/Volumes/Preboot/Cryptexes/OS/Library/Java/JavaVirtualMachines/jdk-17.jdk/Contents/Home/lib/server/libjvm.dylib\' (no such file), \'/Library/Java/JavaVirtualMachines/jdk-17.jdk/Contents/Home/lib/server/libjvm.dylib\' (mach-o file, but is an incompatible architecture (have \'arm64\', need \'x86_64\'))" }', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/j4rs-0.13.0/src/api_tweaks/generic.rs:45:45
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

[2023-08-17 17:48:35:876] [ERROR] Exercise test run failed.
Runtime Error — Failed to run tests for exercise at /Users/ryan/Code/TMC/mooc-java-programming-i/part03-Part03_15.PrintInRange — Runtime Error: Failed to run tests for exercise at /Users/ryan/Code/TMC/mooc-java-programming-i/part03-Part03_15.PrintInRange
	at u._checkLangsResponse (/Users/ryan/.vscode/extensions/moocfi.test-my-code-2.1.5/dist/lib.js:2:436918)
	at /Users/ryan/.vscode/extensions/moocfi.test-my-code-2.1.5/dist/lib.js:2:381755
	at e.andThen (/Users/ryan/.vscode/extensions/moocfi.test-my-code-2.1.5/dist/lib.js:2:543900)
	at /Users/ryan/.vscode/extensions/moocfi.test-my-code-2.1.5/dist/lib.js:2:381738
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by Heliozoa** [comment]
Can you post the output from the following commands?
- `/usr/libexec/java_home -V`
- `file /Library/Java/JavaVirtualMachines/jdk-17.jdk/Contents/Home/lib/server/libjvm.dylib`

**Comment by rjhefley** [comment]
> Can you post the output from the following commands?
> 
>     * `/usr/libexec/java_home -V`

```
╰─ /usr/libexec/java_home -V
Matching Java Virtual Machines (4):
    17.0.8 (arm64) "Oracle Corporation" - "Java SE 17.0.8" /Library/Java/JavaVirtualMachines/jdk-17.jdk/Contents/Home
    11.0.20 (arm64) "Eclipse Adoptium" - "OpenJDK 11.0.20" /Library/Java/JavaVirtualMachines/temurin-11.jdk/Contents/Home
    11.0.20 (arm64) "Eclipse Adoptium" - "OpenJDK 11.0.20" /Users/ryan/Library/Java/JavaVirtualMachines/temurin-11.0.20/Contents/Home
    1.8.0_382 (x86_64) "Eclipse Temurin" - "Eclipse Temurin 8" /Users/ryan/Library/Java/JavaVirtualMachines/temurin-1.8.0_382/Contents/Home
/Library/Java/JavaVirtualMachines/jdk-17.jdk/Contents/Home
```

>     * `file /Library/Java/JavaVirtualMachines/jdk-17.jdk/Contents/Home/lib/server/libjvm.dylib`

```
file /Library/Java/JavaVirtualMachines/jdk-17.jdk/Contents/Home/lib/server/libjvm.dylib
/Library/Java/JavaVirtualMachines/jdk-17.jdk/Contents/Home/lib/server/libjvm.dylib: Mach-O 64-bit dynamically linked shared library arm64
```

**Comment by Heliozoa** [comment]
Thanks. There's definitely some issue when it comes to using aarch64 Java, but I'm not sure where the problem is exactly. Could be that the library we use doesn't support it yet, or that we need to configure it somehow to make it work. I'll look into this further, but in the meantime using  an `x86_64` version should work.

**Comment by rjhefley** [comment]
@Heliozoa thank you so much for your quick replies! I'm somewhat _thankful_ that the problem isn't just me. I look forward to watching this issue progress forward :) This repo is also allowing me to take a look at the rust programming language and trying to follow what's happening.
Thanks again - RJH

**Comment by rjhefley** [comment]
I got good news!! I was able to submit an exercise via the TMC extension using the new Pre-Release Version!!
Thank you so much, @Heliozoa for the quick fix! You deserve a coffee!

**Comment by Heliozoa** [comment]
Great to hear, thanks for your patience and cooperation!
